name: Deploy Hugo site to personal server

on:
  push:
    branches:
      - main  # 或者是你想要触发部署的分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.119.0'
        extended: true

    - name: Show Hugo version
      run: hugo version

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - run: gem install asciidoctor
    
    - name: Run Hugo
      run: |
        alias asciidoctor="asciidoctor --attribute=experimental=true --attribute=icons=font"
        hugo --minify

    
    - name: List generated files
      run: ls -la public

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        rsync -avz --delete public/ $SERVER_USER@$SERVER_IP:/home/lxt/blog/public

    
    - name: SSH into Remote Server and List Directory Files
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        TARGET_DIRECTORY: /home/lxt/blog
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          cd $TARGET_DIRECTORY
          ls -la
        EOF

